<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test.ProposerTest" tests="6" skipped="0" failures="1" errors="0" timestamp="2023-11-08T03:32:10" hostname="MYLESLAPTOP" time="16.858">
  <properties/>
  <testcase name="ProposalSucceeds" classname="test.ProposerTest" time="5.407">
    <failure message="java.lang.AssertionError: expected:&lt;null&gt; but was:&lt;hi&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;null&gt; but was:&lt;hi&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at test.ProposerTest.ProposalSucceeds(ProposerTest.java:317)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:750)
</failure>
  </testcase>
  <testcase name="Proposes" classname="test.ProposerTest" time="2.933"/>
  <testcase name="PrepareFailsThenRetries" classname="test.ProposerTest" time="2.743"/>
  <testcase name="PrepareSucceedsThenProposes" classname="test.ProposerTest" time="2.884"/>
  <testcase name="ClientJoinsSuccessfully" classname="test.ProposerTest" time="0.005"/>
  <testcase name="PrepareReturnsAlternateValue" classname="test.ProposerTest" time="2.884"/>
  <system-out><![CDATA[Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as proposer
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling promise from M1
M1 Handling promise from M2
M1 Received replies from 3 other members
M1 Handling accept from M1
M1 Handling accept from M2
M1 Received replies from 3 other members
Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as proposer
Client M1 committed value: hi
M1 Received replies from 1 other members
M1 Failed prepare, will retry value Proposes with higher ID - 2
Client M1 committed value: STOP
Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as proposer
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Received replies from 1 other members
M1 Failed prepare, will retry value PFTR with higher ID - 2
Client M1 committed value: STOP
Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as proposer
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling promise from M1
M1 Handling promise from M2
M1 Received replies from 3 other members
Client M1 committed value: STOP
Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as acceptor
Client M1 committed value: STOP
Starting to accept client connections
Connecting to server
Accepting new client
Setting up client with ID 1
Acting as proposer
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling not connected
M1 Handling promise from M2
M1 Handling promise from M1
M1 changed to propose new value from M1 : newValue
M1 Received replies from 3 other members
Client M1 committed value: STOP
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
